# Generated by Django 5.0.3 on 2024-03-10 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
    ]
