# Generated by Django 5.0.3 on 2024-03-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_blog', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='commentspost',
            options={'verbose_name_plural': 'PostComment'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Post'},
        ),
        migrations.AlterModelOptions(
            name='replypost',
            options={'verbose_name_plural': 'ReplyPost'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='title',
            new_name='name',
        ),
    ]
